apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: greeter
  name: greeter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: greeter
    spec:
      containers:
      - env:
        - name: LOGGER
          valueFrom:
            configMapKeyRef:
              key: LOGGER
              name: greeter-docker-compose-env
        - name: LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: LOGLEVEL
              name: greeter-docker-compose-env
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              key: NAMESPACE
              name: greeter-docker-compose-env
        - name: SERVICEDIR
          valueFrom:
            configMapKeyRef:
              key: SERVICEDIR
              name: greeter-docker-compose-env
        - name: SERVICES
          value: greeter
        - name: TRANSPORTER
          valueFrom:
            configMapKeyRef:
              key: TRANSPORTER
              name: greeter-docker-compose-env
        image: coffee/services
        name: greeter
        resources: {}
      restartPolicy: Always
status: {}
