apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 80
  - name: "3001"
    port: 3001
    targetPort: 8080
  selector:
    io.kompose.service: traefik
status:
  loadBalancer: {}
