apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: traefik
  name: traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: traefik
    spec:
      containers:
      - args:
        - --web
        - --docker
        - --docker.domain=docker.localhost
        - --logLevel=INFO
        - --docker.exposedbydefault=false
        image: traefik
        name: traefik
        ports:
        - containerPort: 80
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: traefik-claim0
        - mountPath: /traefik.toml
          name: traefik-claim1
      restartPolicy: Always
      volumes:
      - name: traefik-claim0
        persistentVolumeClaim:
          claimName: traefik-claim0
      - name: traefik-claim1
        persistentVolumeClaim:
          claimName: traefik-claim1
status: {}
